config/routes.rb
Rails.application.routes.draw do

  resources :instruments, only: [:index, :show, :edit, :new, :create, :destroy]
  resources :order, only: [:index]
  resources :live_schedules

  devise_for :user
  get '/' => 'tops#index',as:'top'
  get 'tops/search' => 'tops#search'

  get 'receptions/index'
  get 'receptions/show'

  post '/orders' => 'orders#create'

  resources :receptions, only:[:create]
  delete '/instruments/:id' => 'instruments#destroy',as:'destroy_instrument'

  resources :users, only: [:index, :edit, :update] do
    resources :instruments, only: [:index, :show, :edit, :new, :create, :destroy]
end
  get 'users/:id/show' =>'users#show',as:'user_show'
  get 'users/:id/new' => 'users#new', as:'user_new'

  resources :songs

  root 'users#show'



  resources :users do
    member do
     get :following, :followers
    end
  end
  resources :relationships, only: [:create, :destroy]



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/affiliation.rb
class Affiliation < ApplicationRecord
	has_many :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/genre.rb
class Genre < ApplicationRecord
	has_many :users
end

app/models/instrument.rb
class Instrument < ApplicationRecord
	attachment :image
	belongs_to :user
end

app/models/live_schedule.rb
class Schedule < ApplicationRecord
end

app/models/order.rb
class Order < ApplicationRecord

   # has_many :users, through: :receptions
   has_many :receptions
   # accepts_nested_attributes_for :receptions
   belongs_to :user

end

app/models/reception.rb
class Reception < ApplicationRecord

   belongs_to :user
   belongs_to :order

end

app/models/relationship.rb
class Relationship < ApplicationRecord
   belongs_to :following, class_name: "User"
   validates :following_id, presence: true

   belongs_to :follower, class_name: "User"
   validates :follower_id, presence: true
end

app/models/song.rb
class Song < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
   devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

   attachment :user_image
   attachment :image

   has_many :orders
   has_many :receptions
   has_many :instruments

   belongs_to :genre
   belongs_to :affiliation

   has_many :following_relationships, foreign_key: "follower_id", class_name: "Relationship", dependent: :destroy
   has_many :followings, through: :following_relationships

   has_many :follower_relationships, foreign_key: "following_id", class_name: "Relationship", dependent: :destroy
   has_many :followers, through: :follower_relationships


   def following?(other_user)
    following_relationships.find_by(following_id: other_user.id)
   end

   def follow!(other_user)
    following_relationships.create!(following_id: other_user.id)
   end

   def unfollow!(other_user)
    following_relationships.find_by(following_id: other_user.id).destroy
   end
end

app/models/user_genre.rb
class UserGenre < ApplicationRecord
	belongs_to :user
	belongs_to :genre
end

app/models/user_instrument.rb
class UserInstrument < ApplicationRecord
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController

   def new
   end

   def show
   end

   def edit
   end

end

app/controllers/tops_controller.rb
class TopsController < ApplicationController
  def index
      @q = User.ransack(params[:q])
      @users = @q.result(distinct: true)
      @genres = Genre.all
      @affiliations = Affiliation.all
  end

  def search
      @q = User.search(search_params)
      @users = @q.result(distinct: true)
  end

  private
   def user_params
   	   params.require(:user).permit( :first_name,
        	                         :last_name,
        	                         :first_kana,
        	                         :last_kana,
        	                         :tell,
        	                         :email,
        	                         :user_image,
        	                         :titile,
        	                         :body,
                                   :genre_id,
                                   :affiliation_id)
   end

   def search_params
    params.require(:q).permit!
   end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/instruments_helper.rb
module InstrumentsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/receptions_helper.rb
module ReceptionsHelper
end

app/helpers/relationship_helper.rb
module RelationshipHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/helpers/users_helper.rb
module UsersHelper
	 def current_user?(user)
     user == current_user
  end
end

app/views/tops/index.html.erb
<body>
	<div class="col-md-2" style="padding-left: 0">
		<div class="side-box">
			<nav>
				<ul class="side-nav">
					<li>Serch</li>
					<% provide(:first_name, 'All users') %>
					<%= search_form_for(@q, url: tops_search_path) do |f| %>

					<div class="form-group">
						<%#= f.label :first_name, "Name" %>
						<%= f.search_field :first_name_or_last_name_cont, class: "form-control" %>
					</div>
					<%= f.collection_select :genre_id_eq, @genres,:id, :genre_name , {:include_blank => 'Genre'} ,{:class => "form-control"} %>
					<div class="affiliation_select">
						<%= f.collection_select :affiliation_id_eq, @affiliations,:id, :affiliation_name , {:include_blank => 'Instrument'} ,{:class => "form-control"} %>
					</div>
					<%= f.submit "Search",class: 'btn btn-primary btn-block' %>
					<% end %><br>
				</ul>
			</nav>
		</div>
	</div>
	<div class="col-md-10">
		<div class="main-content">
			<div class="main-title">Main Content</div>

			<% @users.each do |user| %>
			<div class="card box1 animated" style="width: 18rem;">
				<%= attachment_image_tag user, :user_image, :fill, 150, 150, format: 'jpeg' %>
				<div class="card-body">
					<div class="top_name_text">
						<%= user.last_name %> <%= user.first_name %><br>
						<h6><%= user.affiliation.affiliation_name %> / <%= user.genre.genre_name %></h6>
					</div>
					<%= user.body%>
				</div>
				<span class="user-go">
					<%= link_to 'Go user Page', user_show_path(user), class: 'btn btn-primary'%>
				</span>
			</div>
			<% end %>
		</div>

	</div>

</body>

app/views/tops/search.html.erb
<head>
	<meta charset="UTF-8">
	<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
</head>

<body>
	<div class="col-md-2" style="padding-left: 0">
		<div class="side-box">
			<nav>
				<ul class="side-nav">
					<li>Serch</li>
					<% provide(:first_name, 'All users') %>
					<%= search_form_for(@q, url: tops_search_path) do |f| %>

					<div class="form-group">
						<%#= f.label :first_name, "Name" %>
						<%= f.search_field :first_name_or_last_name_cont, class: "form-control" %>
					</div>
					<%= f.collection_select :genre_id_eq, Genre.all,:id, :genre_name , {:include_blank => 'Genre'} ,{:class => "form-control"} %>
					<div class="affiliation_select">
						<%= f.collection_select :affiliation_id_eq, Affiliation.all,:id, :affiliation_name , {:include_blank => 'Instrument'} ,{:class => "form-control"} %>
					</div>
					<%= f.submit "Search",class: 'btn btn-primary btn-block' %>
					<% end %><br>
				</ul>
			</nav>
		</div>
	</div>
	<div class="col-md-10">
		<div class="main-content">
			<div class="main-title">Main Content</div>
			<% @users.each do |user| %>
			<div class="card box1 animated" style="width: 18rem;">
				<%= attachment_image_tag user, :user_image, :fill, 150, 150, format: 'jpeg' %>
				<div class="card-body">
					<div class="top_name_text">
						<%= user.last_name %> <%= user.first_name %>
						<h6><%= user.affiliation.affiliation_name %> / <%= user.genre.genre_name %></h6>
					</div>
					<%= user.body%>
				</div>
				<span class="user-go">
					<%= link_to 'Go user Page', user_show_path(user), class: 'btn btn-primary'%>
				</span>
			  </div>
			<% end %>
		</div>
	</div>
</body>