config/routes.rb
Rails.application.routes.draw do

  resources :instruments, only: [:index, :show, :edit, :new, :create, :destroy]
  resources :order, only: [:index]
  resources :live_schedules

  devise_for :user
  get '/' => 'tops#index',as:'top'
  get 'tops/search' => 'tops#search'

  get 'receptions/index'
  get 'receptions/show'

  post '/orders' => 'orders#create'

  resources :receptions, only:[:create]
  delete '/instruments/:id' => 'instruments#destroy',as:'destroy_instrument'

  resources :users, only: [:index, :edit, :update] do
    resources :instruments, only: [:index, :show, :edit, :new, :create, :destroy]
end
  get 'users/:id/show' =>'users#show',as:'user_show'
  get 'users/:id/new' => 'users#new', as:'user_new'

  resources :songs

  root 'users#show'



  resources :users do
    member do
     get :following, :followers
    end
  end
  resources :relationships, only: [:create, :destroy]



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/affiliation.rb
class Affiliation < ApplicationRecord
	has_many :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/genre.rb
class Genre < ApplicationRecord
	has_many :users
end

app/models/instrument.rb
class Instrument < ApplicationRecord
	attachment :image
	belongs_to :user
end

app/models/live_schedule.rb
class Schedule < ApplicationRecord
end

app/models/order.rb
class Order < ApplicationRecord

   # has_many :users, through: :receptions
   has_many :receptions
   # accepts_nested_attributes_for :receptions
   belongs_to :user

end

app/models/reception.rb
class Reception < ApplicationRecord

   belongs_to :user
   belongs_to :order

end

app/models/relationship.rb
class Relationship < ApplicationRecord
   belongs_to :following, class_name: "User"
   validates :following_id, presence: true

   belongs_to :follower, class_name: "User"
   validates :follower_id, presence: true
end

app/models/song.rb
class Song < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
   devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

   attachment :user_image
   attachment :image

   has_many :orders
   has_many :receptions
   has_many :instruments

   belongs_to :genre
   belongs_to :affiliation

   has_many :following_relationships, foreign_key: "follower_id", class_name: "Relationship", dependent: :destroy
   has_many :followings, through: :following_relationships

   has_many :follower_relationships, foreign_key: "following_id", class_name: "Relationship", dependent: :destroy
   has_many :followers, through: :follower_relationships


   def following?(other_user)
    following_relationships.find_by(following_id: other_user.id)
   end

   def follow!(other_user)
    following_relationships.create!(following_id: other_user.id)
   end

   def unfollow!(other_user)
    following_relationships.find_by(following_id: other_user.id).destroy
   end
end

app/models/user_genre.rb
class UserGenre < ApplicationRecord
	belongs_to :user
	belongs_to :genre
end

app/models/user_instrument.rb
class UserInstrument < ApplicationRecord
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController

   def new
   end

   def show
   end

   def edit
   end

end

app/controllers/tops_controller.rb
class TopsController < ApplicationController
  def index
      @q = User.ransack(params[:q])
      @users = @q.result(distinct: true)
      @genres = Genre.all
      @affiliations = Affiliation.all
  end

  def search
      @q = User.search(search_params)
      @users = @q.result(distinct: true)
  end

  private
   def user_params
   	   params.require(:user).permit( :first_name,
        	                         :last_name,
        	                         :first_kana,
        	                         :last_kana,
        	                         :tell,
        	                         :email,
        	                         :user_image,
        	                         :titile,
        	                         :body,
                                   :genre_id,
                                   :affiliation_id)
   end

   def search_params
    params.require(:q).permit!
   end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

   def index
      @user = User.all
      @search = User.ransack(params[:q])
      @result = @search.result
      render "tops/index"
   end

   def new
   end

   def show
       @user = User.find(params[:id])
       @order = Order.new
       @order.receveid = @user.id

       @q = User.ransack(params[:q])
       @users = @q.result(distinct: true)
       @genres = Genre.all
       @affiliations = Affiliation.all
   end

   def edit
       @user = current_user
   end

   def update
   	   @user = current_user
   	   @user.update(user_params)
   	   redirect_to user_show_path(@user.id)
   end

   def create
         @user = current_user
         order = Order.new(order_params)
         order.save
         redirect_to user_show_path(@user.id)
   end

   def destroy
      instruments = Instrument.find(params[:id])
      instruments.destroy
      redirect_to user_show_path(current_user)
   end

   def following
      @user  = User.find(params[:id])
      @users = @user.followings
      render 'show_follow'
   end

   def followers
    @user  = User.find(params[:id])
    @users = @user.followers
    render 'show_follower'
   end

  private
    def user_params
        params.require(:user).permit(:first_name,
        	                           :last_name,
        	                           :first_kana,
        	                           :last_kana,
        	                           :tell,
        	                           :email,
        	                           :user_image,
        	                           :titile,
        	                           :body,
                                     :genre_id,
                                     :affiliation_id)
    end

    def instrument_params
        params.require(:instrument).permit(:instrument_name,
                                           :image)
    end

    def order_params
        params.require(:order).permit(:course,
                                      :budget,
                                      :delivery_date,
                                      :description)
    end
    def genre_params
        params.require(:genre).permit(:genre_name)
    end
    def genre_params
        params.require(:affiliation).permit(:affiliation_name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/instruments_helper.rb
module InstrumentsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/receptions_helper.rb
module ReceptionsHelper
end

app/helpers/relationship_helper.rb
module RelationshipHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/helpers/users_helper.rb
module UsersHelper
	 def current_user?(user)
     user == current_user
  end
end

app/views/songs/new.html.erb
<div class="song-box">
	<h1>Add new song</h1>
</div>

app/views/users/_follow.html.erb
<%= form_for(current_user.following_relationships.build(following_id: @user.id)) do |f| %>
  <div><%= f.hidden_field :following_id %></div>
  <%= f.submit "Follow", class: "btn btn-large btn-primary follow-btn" %>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user?(@user) %>
  <div id="follow_form">
  <% if current_user.following?(@user) %>
    <%= render 'unfollow' %>
  <% else %>
    <%= render 'follow' %>
  <% end %>
  </div>
<% end %>

app/views/users/_stats.html.erb
 <% @user ||= current_user %>
 <div class="stats">
  <div class="following">
    <a href="<%= following_user_path(@user) %>">
      following<br>
      <strong id="following" class="stat1">
        <%= @user.followings.count %>
      </strong>
    </a>
  </div>
  <div class="followers">
    <a href="<%= followers_user_path(@user) %>">
      followers<br>
      <strong id="followers" class="stat2">
        <%= @user.followers.count %>
      </strong>
    </a>
  </div>
</div>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.following_relationships.find_by(following_id: @user.id), html: { method: :delete }) do |f| %>
  <%= f.submit "Unfollow", class: "btn btn-large follow-btn" %>
<% end %>

app/views/users/edit.html.erb
<div class="profiele-height-box">
</div>

<div class="user_edit">Profiele Edit Erea</div>

 <div class="user_edit_text">

  <div class="container">
    <div class="row">
      <div class="col-lg-4">
         <%= form_for(@user) do |f| %>
         <h4></h4>
         <%= attachment_image_tag current_user, :user_image, :fill, 300, 300, format: 'jpeg', class: "user_shot_edit" %><br><br>
         <%= f.attachment_field :user_image %><br>
      </div>
      <div class="col-lg-8">
         <h4> Name</h4>
         <div class="name-edit">
           <%= f.text_field :last_name ,class: "form-control" %><%= f.text_field :first_name ,class: "form-control" %>
         </div><br>
         <div class="name-edit">
           <%= f.text_field :last_kana ,class: "form-control" %><%= f.text_field :first_kana ,class: "form-control" %>
         </div><br>

         <div class="name-edit">
           <%= f.collection_select :affiliation_id, Affiliation.all, :id, :affiliation_name,  {} ,{:class => "form-control"} %>
           <%= f.collection_select :genre_id, Genre.all, :id, :genre_name,  {} ,{:class => "form-control"} %>
         </div>

         <h4>Tell</h4>
         <div class="name-edit">
           <%= f.text_field :tell ,class: "form-control" %>
         </div>

         <h4>Email</h4>
         <div class="name-edit">
           <%= f.text_field :email ,class: "form-control" %>
         </div>

         <h4>Introduction</h4>
         <div class="name-edit">
           <%= f.text_area :body, class: "form-control",:rows =>10 %>
         </div>
         <div class="edit-bottan">
           <%= f.submit ' OK ' ,class: 'btn btn-primary'%>
         </div><br>
    <% end %>
   </div>
  </div>
 </div>
</div>

app/views/users/new.html.erb
<h1>新規投稿</h1>
<!-- form_for部分 -->
<%= form_for(@user) do |f| %>

 <h4>タイトル</h4>
 <%= f.text_field :titile %>
 <h4>本文</h4>
 <%= f.text.erea :body %>

 <%= f.submit '投稿' %>

<% end %>

app/views/users/show.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">

<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">

<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js" integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ" crossorigin="anonymous"></script>

<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.4/css/bootstrap-select.min.css">

<!-- Latest compiled and minified JavaScript -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.4/js/bootstrap-select.min.js"></script>

<!-- (Optional) Latest compiled and minified JavaScript translation files -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.4/js/i18n/defaults-*.min.js"></script>

  <title>MOUSA</title>
</head>
<body>
	<div class="col-md-2" style="padding-left: 0">
		<div class="side-box">
			<nav>
			   <ul class="side-nav">
					<li>Serch</li>
					<% provide(:first_name, 'All users') %>
					<%= search_form_for(@q, url: tops_search_path) do |f| %>

					<div class="form-group">
						<%#= f.label :first_name, "Name" %>
						<%= f.search_field :first_name_or_last_name_cont, class: "form-control" %>
					</div>
					<%= f.collection_select :genre_id_eq, Genre.all,:id, :genre_name , {:include_blank => 'Genre'} ,{:class => "form-control"} %>
					<div class="affiliation_select">
						<%= f.collection_select :affiliation_id_eq, Affiliation.all,:id, :affiliation_name , {:include_blank => 'Instrument'} ,{:class => "form-control"} %>
					</div>
					<%= f.submit "Search",class: 'btn btn-primary btn-block' %>
					<% end %><br>
				</ul>
			</nav>
		</div>
   </div>
   <div class="col-md-10">
	<div class="main-content">
          <div class="name">
             <%= @user.last_name %> <%= @user.first_name %><br>
			 <h3><%= @user.genre.genre_name %></h3>
          </div>
          <div class="user_introduction">
          	 <div class="user_image">
          		<%= attachment_image_tag @user, :user_image, :fill, 150, 150, format: 'jpeg', class: "user_shot_edit" %>
          	 </div><br>
          	 <%= render 'follow_form' %>
             <%= render 'stats' %>
          	 <div class="user-intro-text">
          		<h2>introduction</h2><%= @user.body %>
             </div>
          </div>
		<%#= @user_images %>
		<%  if @user.id == current_user.id %>
			<%= link_to "Edit", edit_user_path(@user), class: 'btn btn-primary' %>
		<% end %>

			<nav>
				<div class="nav nav-tabs" id="nav-tab" role="tablist">

					<a class="nav-item nav-link active" id="nav-home-tab" data-toggle="tab" href="#nav-home" role="tab" aria-controls="nav-home" aria-selected="true">Track</a>

					<a class="nav-item nav-link" id="nav-profile-tab" data-toggle="tab" href="#nav-profile" role="tab" aria-controls="nav-profile" aria-selected="false">Use Instrument</a>

					<a class="nav-item nav-link" id="nav-live-tab" data-toggle="tab" href="#nav-live" role="tab" aria-controls="nav-live" aria-selected="false">Live Schedule</a>
        <% if @user.id != current_user.id %>
					<a class="nav-item nav-link" id="nav-contact-tab" data-toggle="tab" href="#nav-contact" role="tab" aria-controls="nav-contact" aria-selected="false">Job Request</a>

        <% elsif @user.id == current_user.id %>
					<a class="nav-item nav-link" id="nav-reception-tab" data-toggle="tab" href="#nav-reception" role="tab" aria-controls="nav-reception" aria-selected="false">Job Reception</a>

					<a class="nav-item nav-link" id="nav-order_history-tab" data-toggle="tab" href="#nav-order_history" role="tab" aria-controls="nav-order_history" aria-selected="false">Order History</a>
		<% else %>

	    <% end %>
				</div>
			</nav>

			<div class="tab-content" id="nav-tabContent">
				<div class="tab-pane fade show active" id="nav-home" role="tabpanel" aria-labelledby="nav-home-tab">
					<div class="add-song"><br>
						<h1 class="head-text">Tracks</h1>
                       <%= link_to "Add", new_song_path, class: 'btn btn-primary' %>
                   </div>
				</div>
	   <div class="tab-pane fade" id="nav-profile" role="tabpanel" aria-labelledby="nav-profile-tab">
          <br>
		  <h2>Use Instrument</h2>
		  <% if @user.id == current_user.id %>
		  <%= link_to "Add", new_instrument_path, class: 'btn btn-primary' %>
          <% end %>
		  <table class="table table-hover">
			 <thead>
				  <tr>
					 <th scope="col">Image</th>
					 <th scope="col">Instrument-name</th>
					 <th scope="col">Introduction</th>
					 <th scope="col"></th>
				  </tr>
			  </thead>
			  <% @user.instruments.each do |instrument| %>
				  <tbody>
					  <td style="width: 200px">
					      <%= attachment_image_tag instrument, :image, :fill, 80, 80, format: 'jpeg' %></td>
					  <td style="width: 250px"><%=link_to instrument.instrument_name,instrument_path(instrument.id) %></td>
					  <td><%= instrument.introduction %></td>
					  <td style="width: 150px">
				<%  if @user.id == current_user.id %>
					  	<%= link_to "edit", edit_instrument_path(instrument.id), class: 'btn btn-primary' %>
					  	<%= link_to "delete", user_instrument_path(instrument.id), class: 'btn btn-danger', method: :delete, "data-confirm" => "本当に削除しますか？" %></td>
			    <% end %>
				  </tbody>
			 <% end %>
		  </table>
		  </div>

		  <div class="tab-pane fade" id="nav-live" role="tabpanel" aria-labelledby="nav-live-tab"><br>
		  	  <h2>Live Schedule</h2>
		     <% if @user.id == current_user.id %>
		           <%#= link_to "Add", new_live_schedule_path, class: 'btn btn-primary' %>
             <% end %>
		  	  <table class="table table-hover">
			 <thead>
				  <tr>
					 <th scope="col">Image</th>
					 <th scope="col">Title</th>
					 <th scope="col">Date</th>
					 <th scope="col">Location</th>
					 <th scope="col">Price</th>
				  </tr>
			  </thead>
			  <%# @user.instruments.each do |instrument| %>
				  <tbody>
					  <td style="width: 200px">
					      <%#= attachment_image_tag instrument, :image, :fill, 80, 80, format: 'jpeg' %></td>
					  <td style="width: 250px"><%#=link_to instrument.instrument_name,instrument_path(instrument.id) %></td>
					  <td><%#= instrument.introduction %></td>
					  <td style="width: 200px">
					  	<%#= link_to "edit", edit_instrument_path(instrument.id), class: 'btn btn-primary' %>
					  	<%#= link_to "delete", user_instrument_path(instrument.id), class: 'btn btn-danger', method: :delete, "data-confirm" => "本当に削除しますか？" %></td>
				  </tbody>
			 <%# end %>
		  </table>
		  </div>

				<div class="tab-pane fade" id="nav-contact" role="tabpanel" aria-labelledby="nav-contact-tab"><br>
				  <h2>Order Content</h2><br>
				   <div class="order-box">
                     <%= form_for @order do |f| %>
                     <div class="order-box">
					 <%= f.select :course, [["Compose","Compose"],["Arrangement","Arrangement"],["Solo","Solo"],["Bucking","Bucking"],["Live suport","Live suport"],["Cast request","Cast request"]], {:include_blank => 'Course'} ,{:class => "form-control"} %><br>
					 <%= f.select :budget, [["＄30〜50", "＄30〜50"], ["＄50〜100", "＄50〜100"], ["＄100〜200", "＄100〜200"], ["＄300〜400", "＄300〜400"], ["＄400〜500", "＄400〜500"], ["＄500〜600", "＄500〜600"], ["＄60〜", "＄60〜"]], {:include_blank => 'Budget'} ,{:class => "form-control"}  %><br>
					 </div>
					 <%= f.hidden_field :receveid%>
					 <span></span>Estimated delivery time</span><br>
                     <%= f.text_field :delivery_date %><br><br>

                     <span></span>Reply Deadline</span><br>
                     <%= f.text_field :reply_deadline %><br><br>

                     <span></span>More detail</span><br>
                     <%= f.text_area :description, :size=>"60x5" %>

                     <%= f.submit 'Order', class: 'btn btn-primary' %>
                     <% end %><br>
                  </div>
				</div>
				<div class="tab-pane fade" id="nav-reception" role="tabpanel" aria-labelledby="nav-reception-tab">
					<br><h2>Job Reception</h2>
					<table class="table table-hover">
						<thead>
							<tr>
								<th scope="col">Image</th>
								<th scope="col">Name</th>
								<th scope="col">Course</th>
								<th scope="col">Budget</th>
								<th scope="col">Description</th>
								<th scope="col">Delivery_date</th>
								<th scope="col">Reply Deadline</th>
							</tr>
						</thead>
						<% @user.receptions.each do |reception| %>
						   <tbody>
							 <td style="width: 120px">
							 	<%= link_to user_show_path(reception.order.user) do %>
							 	<%= attachment_image_tag reception.order.user, :user_image, :fill, 80, 80, format: 'jpeg' %>
							 		<% end %>
							 	</td>
							 <td style="width: 120px"><%= reception.order.user.first_name %><%= reception.order.user.last_name %></td>
							 <td style="width: 130px"><%= reception.order.course %></td>
							    <td style="width: 120px"><%= reception.order.budget %></td>
							    <td style="width: 450px"><%= reception.order.description %></td>
								<td style="width: 120px"><%= reception.order.delivery_date %></td>
								<td style="width: 120px"><%= reception.order.reply_deadline %></td>
							</tbody>
						 <% end %>
						</table>
						<%#= reception.order.budget %>
						<%#= @order.description %>
				</div>
				<div class="tab-pane fade" id="nav-order_history" role="tabpanel" aria-labelledby="nav-order_history-tab">
					<br><h2>Order History</h2>
					<table class="table table-hover">
						<thead>
							<tr>
								<th scope="col">Image</th>
								<th scope="col">Name</th>
								<th scope="col">Course</th>
								<th scope="col">Budget</th>
								<th scope="col">Description</th>
								<th scope="col">Delivery_date</th>
								<th scope="col">Reply Deadline</th>
							</tr>
						</thead>
						<% @user.orders.each do |order| %>
						<% order.receptions.each do |reception| %>
						   <tbody>
							 <td style="width: 120px">
							 	<%= link_to user_show_path(reception.user) do %>
								 	<%= attachment_image_tag reception.user, :user_image, :fill, 80, 80, format: 'jpeg' %>
							 	<% end %>
							 	</td>
							 <td style="width: 120px"><%= reception.user.last_name %> <%= reception.user.first_name %></td>
							 <td style="width: 130px"><%= order.course %></td>
							    <td style="width: 120px"><%= order.budget %></td>
							    <td style="width: 450px"><%= order.description %></td>
								<td style="width: 120px"><%= order.delivery_date %></td>
								<td style="width: 120px"><%= order.reply_deadline %></td>
							</tbody>
						 <% end %>
						 <% end %>
						</table>
				</div>
	      </div>
       </div>
	</div>
   </div>
</body>
</html>

app/views/users/show_follow.html.erb
<div class="follwing-box">
</div>

<div class="following-title">
	Followings
 </div>

<div class="followings-cards">
  <% @user.followings.each do |user| %>
      <div class="card box1 animated" style="width: 18rem;">
				<%= attachment_image_tag user, :user_image, :fill, 150, 150, format: 'jpeg' %>
				<div class="card-body">
					<div class="top_name_text">
						<%= user.last_name %> <%= user.first_name %><br>
						<h6><%= user.affiliation.affiliation_name %> / <%= user.genre.genre_name %></h6>
					</div>
					<%= user.body%>
				</div>
				<span class="user-go">
					<%= link_to 'Go user Page', user_show_path(user), class: 'btn btn-primary'%>
				</span>
	  </div>
 <% end %>
</div>

app/views/users/show_follower.html.erb
<div class="follwing-box">
</div>

<div class="following-title">
	Followers
</div>

<div class="followings-cards">
	<% @user.followers.each do |user| %>
	<div class="card box1 animated" style="width: 18rem;">
		<%= attachment_image_tag user, :user_image, :fill, 150, 150, format: 'jpeg' %>
		<div class="card-body">
			<div class="top_name_text">
				<%= user.last_name %> <%= user.first_name %><br>
				<h6><%= user.affiliation.affiliation_name %> / <%= user.genre.genre_name %></h6>
			</div>
			<%= user.body%>
		</div>
		<span class="user-go">
			<%= link_to 'Go user Page', user_show_path(user), class: 'btn btn-primary'%>
		</span>
	</div>
	<% end %>
</div>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>