config/routes.rb
Rails.application.routes.draw do

  resources :instruments, only: [:index, :show, :edit, :new, :create, :destroy]
  resources :order, only: [:index]
  resources :live_schedules

  devise_for :user
  get '/' => 'tops#index',as:'top'
  get 'tops/search' => 'tops#search'

  get 'receptions/index'
  get 'receptions/show'

  post '/orders' => 'orders#create'

  resources :receptions, only:[:create]
  delete '/instruments/:id' => 'instruments#destroy',as:'destroy_instrument'

  resources :users, only: [:index, :edit, :update] do
    resources :instruments, only: [:index, :show, :edit, :new, :create, :destroy]
end
  get 'users/:id/show' =>'users#show',as:'user_show'
  get 'users/:id/new' => 'users#new', as:'user_new'

  resources :songs

  root 'users#show'



  resources :users do
    member do
     get :following, :followers
    end
  end
  resources :relationships, only: [:create, :destroy]



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/affiliation.rb
class Affiliation < ApplicationRecord
	has_many :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/genre.rb
class Genre < ApplicationRecord
	has_many :users
end

app/models/instrument.rb
class Instrument < ApplicationRecord
	attachment :image
	belongs_to :user
end

app/models/live_schedule.rb
class Schedule < ApplicationRecord
end

app/models/order.rb
class Order < ApplicationRecord

   # has_many :users, through: :receptions
   has_many :receptions
   # accepts_nested_attributes_for :receptions
   belongs_to :user

end

app/models/reception.rb
class Reception < ApplicationRecord

   belongs_to :user
   belongs_to :order

end

app/models/relationship.rb
class Relationship < ApplicationRecord
   belongs_to :following, class_name: "User"
   validates :following_id, presence: true

   belongs_to :follower, class_name: "User"
   validates :follower_id, presence: true
end

app/models/song.rb
class Song < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
   devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

   attachment :user_image
   attachment :image

   has_many :orders
   has_many :receptions
   has_many :instruments

   belongs_to :genre
   belongs_to :affiliation

   has_many :following_relationships, foreign_key: "follower_id", class_name: "Relationship", dependent: :destroy
   has_many :followings, through: :following_relationships

   has_many :follower_relationships, foreign_key: "following_id", class_name: "Relationship", dependent: :destroy
   has_many :followers, through: :follower_relationships


   def following?(other_user)
    following_relationships.find_by(following_id: other_user.id)
   end

   def follow!(other_user)
    following_relationships.create!(following_id: other_user.id)
   end

   def unfollow!(other_user)
    following_relationships.find_by(following_id: other_user.id).destroy
   end
end

app/models/user_genre.rb
class UserGenre < ApplicationRecord
	belongs_to :user
	belongs_to :genre
end

app/models/user_instrument.rb
class UserInstrument < ApplicationRecord
end

app/controllers/tops_controller.rb
class TopsController < ApplicationController
  def index
      @q = User.ransack(params[:q])
      @users = @q.result(distinct: true)
      @genres = Genre.all
      @affiliations = Affiliation.all
  end

  def search
      @q = User.search(search_params)
      @users = @q.result(distinct: true)
  end

  private
   def user_params
   	   params.require(:user).permit( :first_name,
        	                         :last_name,
        	                         :first_kana,
        	                         :last_kana,
        	                         :tell,
        	                         :email,
        	                         :user_image,
        	                         :titile,
        	                         :body,
                                   :genre_id,
                                   :affiliation_id)
   end

   def search_params
    params.require(:q).permit!
   end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/instruments_helper.rb
module InstrumentsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/receptions_helper.rb
module ReceptionsHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/helpers/users_helper.rb
module UsersHelper
	 def current_user?(user)
     user == current_user
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mousa</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  <!-- bootstrap -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">

  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js" integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ" crossorigin="anonymous"></script>

  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm" crossorigin="anonymous"></script>

  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.5.1/animate.min.css" >

  </head>
  <header zーindex>
    <div head-context>
     <div class="col-md-3" style="margin-top: 12px;">
      <%= link_to'MOUSA',top_path,class: "logo" %>
     </div>
     <div class="col-md-9" style="margin-top: 25px;">
      <nav class="nav-top">
        <ul>
         <% if user_signed_in? %>
          <li> <%= link_to'Home',top_path %></li>
          <li><%= link_to'My page',user_show_path(current_user) %></li>
          <li><%= link_to 'Log out',destroy_user_session_path, method: :delete %></li>
           <% else %>
              <li><%= link_to'Home',top_path %></li>
          <li><%= link_to'Sign up',new_user_registration_path %></li>
          <li><%= link_to'Log in',user_session_path %></li>
         <% end %>
        </ul>
      </nav>
     </div>
    </div>
  </header>
  <body>
    <%= yield %>
  </body>
</html>